### ISSUE TITLE
Some error when run generate

### ISSUE THREAD

**Issue by herryliq** [cmeza20/spring-data-generator#1]
When I run the follow command:
mvn spring-data-generator:repositories

There was some error.
[ERROR] Failed to execute goal com.cmeza:spring-data-generator:1.1.0:repositorie
s (default-cli) on project airportBackEnd: Unable to parse configuration of mojo
 com.cmeza:spring-data-generator:1.1.0:repositories for parameter entity-package
: Cannot assign configuration entry 'entity-package' with value 'com.kanghui.mod
el' of type java.lang.String to property of type java.lang.String[] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.

**Comment by cmeza20** [comment]
Hi @herryliq 

The problem is the maven version

Instead of
```xml
<configuration>
	<entity-package>com.kanghui.model</entity-package>
</configuration>
```

Try
```xml
<configuration>
        <entity-package>
                  <param>com.kanghui.model</param>
        </entity-package>
</configuration>
```

Tell me about your results

**Comment by herryliq** [comment]
@cmeza20 
With your suggestion, it was work well.
Thank you very much, but I think you should change the description about this because some people will encounter the same problem .
