### ISSUE TITLE
May be use wildcard in entityscan or list the specifics entites

### ISSUE THREAD

**Issue by jzlima** [cmeza20/spring-data-generator#18]
May be use wildcard in entityscan or list the specifics entites

**Comment by cmeza20** [comment]
Hello @jzlima 
entityPackage does not support wildcards, but you can assign the entities you need:
1. Property "onlyAnnotations" = true
2. Entities:

```
@Entity
//@SDGenerate   ->  Optional: Include to classes scan
//@SDNoGenerate   ->  Optional: Exclude to classes scan
public class Account {
}
```
