### ISSUE TITLE
Function requirement suggest

### ISSUE THREAD

**Issue by herryliq** [cmeza20/spring-data-generator#2]
The generate code like follows:
/**
* Generated by Spring Data Generator on 10/05/2017
*/ 
public interface CityAirportRepository extends JpaRepository<CityAirport, Long> {

}

When I use these code with Spring Data JPA , I need add annotation @Repository for every Repository,
can you add this annotation when generate code in the future release plan?

**Comment by cmeza20** [comment]
Hi @herryliq

Of course, the @Repository annotation is added in the next version.

The next version has already been released [v1.1.1](https://github.com/cmeza20/spring-data-generator/blob/master/CHANGELOG.md)

Greetings.

**Comment by herryliq** [comment]
Hi @cmeza20 
Thank you!
