### ISSUE TITLE
Provide option to strip meta-data  / generated date

### ISSUE THREAD

**Issue by ScottyJayDub** [cmeza20/spring-data-generator#25]
E.g. - "Generated by Spring Data Generator on 28/01/2022".

Whilst I probably should be parking the generated repositories in generated-sources, and .gitignore that directory.  I'm not doing so currently to keep things simple.

Having the date change every time I run a build means I have changes I have to manage in source control.  It would be great if I could turn this off and relieve myself of that burden.

Any thoughts on this?  Is there a workaround?

**Comment by cmeza20** [comment]
```xml
<dependency>
  <groupId>com.cmeza</groupId>
  <artifactId>spring-data-generator</artifactId>
  <version>1.1.9</version>
</dependency>
```

Hello, I released the latest version; in it you can already disable class comments.

If every time you run your project you regenerate the classes you must disable the "override" option in the configuration.
Or in any case use the option generated by plugin

-- Annotation
```java
@SDGenerator(        
        overwrite = false,
        withComments= false
)
```
-- Plugin
```xml
<build>
	<plugins>
		<plugin>
			<groupId>com.cmeza</groupId>
			<artifactId>spring-data-generator</artifactId>
			<version>1.1.9</version>
			<configuration>			
                                <overwrite>false</overwrite>	
                                <with-comments>false</with-comments>
			</configuration>
		</plugin>
	</plugins>
</build>
```



Greetings
