### ISSUE TITLE
Multimodule maven project - generating in submodule absolute path issue

### ISSUE THREAD

**Issue by slavomir-sidor** [cmeza20/spring-data-generator#26]
When you run plugin in multimodule mvn project in submodule, the absolute path of generated files are wrong, its relative to path you are building  in .
public class GeneratorUtils {

    private GeneratorUtils() {
    }

    public static String getAbsolutePath(){
        try {
            return new File(".").getCanonicalPath() + "/src/main/java/";
        } catch (IOException e) {
            return null;
        }
    }

**Comment by cmeza20** [comment]
Hello, if you are using a multi-module project, it is necessary to add the "plugin" in the submodule, not in the main module.

If it were not the case, could you send me some clue of how your project is configured.

Greetings.

**Comment by schegolevalex** [comment]
I faced the same issue. Apparently we are talking about a multi-module project, and binding the plugin to the maven phase in submodule. Like this:
```
           <plugin>
                <groupId>com.cmeza</groupId>
                <artifactId>spring-data-generator</artifactId>
                <version>2.0.0</version>
                <executions>
                    <execution>
                        <id>generateRepositories</id>
                        <goals>
                            <goal>repositories</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <entity-package>
                                <param>com.mypackage.entities</param>
                            </entity-package>
                            <repository-package>com.mypackage.repositories</repository-package>
                            <repository-postfix>Repository</repository-postfix>
                            <manager-package>com.mypackage.managers</manager-package>
                            <manager-postfix>Manager</manager-postfix>
                            <only-annotations>false</only-annotations>
                            <overwrite>true</overwrite>
                            <lombok-annotations>false</lombok-annotations>
                            <with-comments>false</with-comments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
With that settings generated classes will be created at src/main/java in parent module, not in child one.
For myself I did this #32
