### ISSUE TITLE
Config option to not extend any interface (ie JpaSpecificationExecutor)

### ISSUE THREAD

**Issue by aam2elm** [cmeza20/spring-data-generator#33]
A configuration option to omit any default extension of any interface would be nice, I for example do not want to extend **JpaSpecificationExecutor** interface in my generated repos.

**Comment by cmeza20** [comment]
Hello, in the new version 2.0.1 you can omit the **JpaSpecificationExecutor** interface

Programmatically:

![image](https://github.com/cmeza20/spring-data-generator/assets/9298942/9866b282-c0c6-4b22-8bf7-9484dd8aa91a)

Plugin

![image](https://github.com/cmeza20/spring-data-generator/assets/9298942/074b35da-c90b-4d86-8bf3-224e0d52b70a)

Geetings
