### ISSUE TITLE
Repository Error: @Id not found

### ISSUE THREAD

**Issue by zerouwar** [cmeza20/spring-data-generator#6]
My entity is generated by idea tool and @Id is marked with getter method,not the property.`spring-data-generator` can not find @Id.

**Comment by cmeza20** [comment]
Hi @zerouwar 

I just posted a new version (1.1.3)
The annotation **@Id** Id is now supported from the getter method

The **@EmbeddedId** annotation is also supported

```xml
<dependency>
  <groupId>com.cmeza</groupId>
  <artifactId>spring-data-generator</artifactId>
  <version>1.1.3</version>
</dependency>
```

Best regards

**Comment by zerouwar** [comment]
It works!Thank you for quick reply

It is a great utils
